[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Set correct MIME types for all files in assets/css/
[[headers]]
  for = "/assets/css/*"
  [headers.values]
    Content-Type = "text/css"

# Set correct MIME types for all files in assets/js/
[[headers]]
  for = "/assets/js/*"
  [headers.values]
    Content-Type = "application/javascript" 