// Generated by scripts/measure-lighthouse.mjs — do not edit by hand.
// Re-run with: npm run build && npm run measure

export interface LighthouseScores {
  performance: number
  accessibility: number
  'best-practices': number
  seo: number
}

export const lighthouse: {
  measuredAt: string
  tool: string
  mobile: LighthouseScores
  desktop: LighthouseScores
} | null = null
